# Using SettingsLogic, see https://github.com/binarylogic/settingslogic
# settings loaded in model/settings.rb
# Accessible through Settings.key
# Environment specific settings expected in config/settings/{environment_name}.yml
# Add overwrites in here
test:
  host:
    name: localhost
    port: 3030
  smtp:
    address: smtp.address
    port: smtp.port
    domain: domain.com
    user_name: username
    authentication: login
    password: password
  db:
    adapter: postgresql
    encoding: unicode
    database: myapp_test
    pool: 5
    username: postgres
    password: ''
  exception_notification:
    email_prefix: '[BAW travis test]'
  devise:
    pepper: 2a1dd780abf48819876cd0b74b5a988b
    expire_auth_token_on_timeout: false
    secret_key: 8050140a1d4824520eb759778ada63fe
  secret_token: 286c3a382cc5f94bc4003023f9486845
  paths:
    image_magick_dir: <%= Rails.root %>/vendor/bin/imagemagick
    ######################################################
    # these paths must align with the paths used by the harvester settings file
    ######################################################
    original_audios:
      - <%= Rails.root %>/tmp/_original_audio
    cached_spectrograms:
      - <%= Rails.root %>/tmp/_cached_spectrogram
    cached_audios:
      - <%= Rails.root %>/tmp/_cached_audio
  audio_tools:
    ffmpeg_executable: ffmpeg
    ffprobe_executable: ffprobe
    mp3splt_executable: mp3splt
    sox_executable: .sox
    wavpack_executable: wvunpack
    imagemagick_convert_executable: convert
    imagemagick_identify_executable: identify
  server_version: 0.0.1